language: java

addons:
  sonarcloud:
    organization: "nascimento-github"

script:
mvn sonar:sonar \
  -Dsonar.organization=nascimento-github \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=730784478ecf70bf582b2501c5c8c131c32db75a
